apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: confluent-cp
spec:
  destination:
    namespace: confluent-cp
    server: https://kubernetes.default.svc
  source:
    path: data/CP
    repoURL: https://github.com/sotojuan2/cfk-control-plane-argocd
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
