apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: confluent-cloud
spec:
  destination:
    namespace: confluent-cloud
    server: 'https://kubernetes.default.svc'
  source:
    path: data/CC
    repoURL: https://github.com/sotojuan2/cfk-control-plane-argocd
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
