apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
data:
  key1: value1
  key2: value2
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: demo-topic-456
spec:
  replicas: 3
  partitionCount: 6
  configs:
    cleanup.policy: "delete"
