apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: demo-topic-rrrr
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 1
  configs:
    message.timestamp.type: "LogAppendTime"
  kafkaRest:
    endpoint: http://host.docker.internal:8090
