apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: invalid-topic-123 # ❌ No empieza con "demo-topic-"
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 6
  configs:
    cleanup.policy: "delete"
