---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: demo-topic-456
  labels:
    strimzi.io/cluster: my-cluster
    environment: test
spec:
  partitions: 5
  replicas: 3
  config:
    retention.ms: 86400000
    cleanup.policy: delete
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: demo-topic-789
  labels:
    strimzi.io/cluster: my-cluster
    environment: test
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: 259200000
    min.insync.replicas: 2
